Repository GSG-G11/muslim-guide, pull requests merged in 2022-04, with the labels that each got.

#2 create basic folder strucure
  .env.example
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/assets/favicon.png
  public/assets/frame.png
  public/assets/hands.png
  public/assets/logo.png
  public/assets/pray.png
  public/assets/quran.png
  public/index.html
  src/App.css
  src/App.jsx
  src/components/BackArrow.jsx
  src/components/Button.jsx
  src/components/Container.jsx
  src/components/Input.jsx
  src/components/index.js
  src/components/styles/BackArrow.css
  src/index.jsx
Labels: Done

#6 add Home Page component
  public/index.html
  src/App.jsx
  src/Pages/Home/Home.css
  src/Pages/Home/Home.jsx
  src/Pages/index.js
Labels: review

#9 Add Prayer Page
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/index.js
  src/Pages/prayerPage/Prayer.jsx
  src/Pages/prayerPage/style.css
  src/Pages/quranPage/quran.js
  src/colors.json
  src/components/Container.jsx
  src/components/PrayerTime.jsx
Labels: Awaiting Review

#8 7 azkar page
  src/App.css
  src/Pages/Azkar/Azkar.css
  src/Pages/Azkar/Azkar.jsx
  src/Pages/index.js
  src/components/Header.jsx
  src/components/styles/BackArrow.css
  src/components/styles/Header.css
  src/utils.js
Labels: Awaiting Review

#11 10 zekr page
  src/App.jsx
  src/Pages/Azkar/Azkar.css
  src/Pages/Azkar/Azkar.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Zekr/Zekr.css
  src/Pages/Zekr/Zekr.jsx
  src/Pages/index.js
  src/Pages/prayerPage/Prayer.jsx
  src/components/BackArrow.jsx
  src/index.jsx
Labels: Awaiting Review

#16 4 quran page
  src/App.jsx
  src/Pages/Home/Home.css
  src/Pages/Zekr/Zekr.css
  src/Pages/index.js
  src/Pages/prayerPage/Prayer.jsx
  src/Pages/prayerPage/style.css
  src/Pages/quranPage/Quran.jsx
  src/Pages/quranPage/quran.js
  src/Pages/quranPage/style.css
  src/assets/favicon.png
  src/assets/frame.jpg
  src/assets/hands.png
  src/assets/logo.png
  src/assets/pray.png
  src/assets/quran.png
  src/components/Header.jsx
  src/components/index.js
Labels: Awaiting Review

#17 13 404 page
  src/App.jsx
  src/Pages/404/404.css
  src/Pages/404/404.jsx
Labels: Done

#19 Fix images paths and fix colors
  src/Pages/Azkar/Azkar.jsx
  src/Pages/Home/Home.jsx
  src/assets/logo.png
  src/assets/mosque.png
  src/utils.js
Labels: Awaiting Review

#20 14 refactoring
  src/App.css
  src/App.jsx
  src/Context/Context.jsx
  src/Pages/Azkar/Azkar.css
  src/Pages/Azkar/Azkar.jsx
  src/Pages/Home/Home.css
  src/Pages/Home/Home.jsx
  src/Pages/Zekr/Zekr.jsx
  src/Pages/index.js
  src/colors.json
  src/components/AzkarCard.jsx
  src/components/BackArrow.jsx
  src/components/RitualCard.jsx
  src/components/ZekrCard.jsx
  src/components/index.js
  src/components/styles/BackArrow.css
Labels: Awaiting Review
